name = "envision-health-backend"
main = "src/index.ts"
compatibility_date = "2024-03-20"

[ai]
binding = "AI"

[[d1_databases]]
binding = "DB"
database_name = "envision_health_db"
database_id = "3b6b7d97-ff46-4d7e-a3a7-8ec87fb1ec97"

